title: "Kunyu (Chris) Lin"
description: "Technical Solutions Consultant — Ad Tech, Mobile Engineering, Product Solutions"
author:
  name: Kunyu (Chris) Lin
  email: "p158276@gmail.com"

# URL settings
baseurl: ""
url: "https://p158276.github.io"

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - swipner.md
