theme: minima
author:
  name: Kunyu(Chris) Lin
  email: p158276@gmail.com

# URL settings
baseurl: "" # Leave this empty unless your site is in a subdirectory
url: "https://p158276.github.io" # Your GitHub Pages URL

header_pages:
  - about.md
  - portfolio.md

minima:
  skin: classic
  social_links: 
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/kunyu-lin/" }
# Build settings
markdown: kramdown
kramdown:
  input: GFM 
